ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'


# New Section

In [42]:
import numpy as np
import torch

In [12]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [13]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [14]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [15]:
w=torch.randn(2,3, requires_grad=True)
b=torch.randn(2,requires_grad=True)

In [16]:
print(w)
print(b)

tensor([[ 0.3245, -0.1612,  0.7837],
        [-0.7727,  1.0760,  1.4809]], requires_grad=True)
tensor([-0.8429, -1.7138], requires_grad=True)


In [17]:
def model(x):
  return x @ w.t() + b

In [18]:
preds= model(inputs)
print(preds)

tensor([[ 45.7461,  77.6555],
        [ 64.6598, 117.4435],
        [ 51.2453, 161.1465],
        [ 54.3238,  20.5376],
        [ 60.9327, 151.9360]], grad_fn=<AddBackward0>)


In [20]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [21]:
#MSE
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [23]:
#compute the loss
loss=mse(preds,targets)
print(loss)

tensor(1025.4341, grad_fn=<DivBackward0>)


In [24]:
#compute gradients
loss.backward()

In [25]:
print(w)
print(w.grad)

tensor([[ 0.3245, -0.1612,  0.7837],
        [-0.7727,  1.0760,  1.4809]], requires_grad=True)
tensor([[-1547.1541, -2770.5239, -1433.0388],
        [ 1019.4747,  1637.1094,   942.0954]])


In [26]:
preds=model(inputs)


In [27]:
preds

tensor([[ 45.7461,  77.6555],
        [ 64.6598, 117.4435],
        [ 51.2453, 161.1465],
        [ 54.3238,  20.5376],
        [ 60.9327, 151.9360]], grad_fn=<AddBackward0>)

In [29]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [32]:
loss=mse(preds,targets)
print(loss)

tensor(1025.4341, grad_fn=<DivBackward0>)


In [31]:
preds=model(inputs)
preds

tensor([[ 45.7461,  77.6555],
        [ 64.6598, 117.4435],
        [ 51.2453, 161.1465],
        [ 54.3238,  20.5376],
        [ 60.9327, 151.9360]], grad_fn=<AddBackward0>)

In [33]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-1547.1541, -2770.5239, -1433.0388],
        [ 1019.4747,  1637.1094,   942.0954]])
tensor([-20.8185,  13.7438])


In [35]:
with torch.no_grad():
  w -=w.grad * 1e-5
  b -=b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [36]:
print(w)
print(b)

tensor([[ 0.3400, -0.1335,  0.7980],
        [-0.7829,  1.0597,  1.4715]], requires_grad=True)
tensor([-0.8427, -1.7140], requires_grad=True)


In [37]:
preds=model(inputs)
loss=mse(preds, targets)
print(loss)

tensor(872.4917, grad_fn=<DivBackward0>)


In [54]:
for i in range(1):
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -=w.grad * 1e-5
        b -=b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [55]:
preds=model(inputs)
preds

tensor([[ 56.9756,  69.9373],
        [ 82.6953, 101.5614],
        [117.8845, 131.5237],
        [ 20.8677,  36.6359],
        [102.7272, 120.5718]], grad_fn=<AddBackward0>)

In [56]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [57]:
import torch.nn as nn

In [58]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                   [102, 43, 37], [69, 96, 70], [73, 67, 43],
                   [91, 88, 64], [87, 134, 58], [102, 43, 37],
                   [69, 96, 70], [73, 67, 43], [91, 88, 64],
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]],
                  dtype='float32')

In [59]:
targets = np.array([[56, 70], [81, 101], [119, 133],
                    [22, 37], [103, 119], [56, 70],
                    [81, 101], [119, 133], [22, 37],
                    [103, 119], [56, 70], [81, 101],
                    [119, 133], [22, 37], [103, 119]],
                   dtype='float32')

In [60]:
inputs=torch.from_numpy(inputs)

In [61]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [62]:
targets=torch.from_numpy(targets)

In [63]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [64]:
from torch.utils.data import TensorDataset

In [65]:
train_ds=TensorDataset(inputs,targets)

In [66]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [67]:
from torch.utils.data import DataLoader

In [68]:
batch_size = 5
train_dl=DataLoader(train_ds, batch_size, shuffle=True)

In [70]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.]])
tensor([[ 81., 101.],
        [ 56.,  70.],
        [103., 119.],
        [119., 133.],
        [ 22.,  37.]])


In [71]:
model= nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3266, -0.0348,  0.0928],
        [ 0.0857,  0.2077,  0.3324]], requires_grad=True)
Parameter containing:
tensor([0.2070, 0.1051], requires_grad=True)


In [72]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3266, -0.0348,  0.0928],
         [ 0.0857,  0.2077,  0.3324]], requires_grad=True),
 Parameter containing:
 tensor([0.2070, 0.1051], requires_grad=True)]

In [73]:
preds=model(inputs)

In [74]:
preds

tensor([[-21.9723,  34.5701],
        [-26.6316,  47.4553],
        [-27.4825,  54.6728],
        [-31.1655,  30.0743],
        [-19.1679,  49.2273],
        [-21.9723,  34.5701],
        [-26.6316,  47.4553],
        [-27.4825,  54.6728],
        [-31.1655,  30.0743],
        [-19.1679,  49.2273],
        [-21.9723,  34.5701],
        [-26.6316,  47.4553],
        [-27.4825,  54.6728],
        [-31.1655,  30.0743],
        [-19.1679,  49.2273]], grad_fn=<AddmmBackward0>)

In [75]:
import torch.nn.functional as F

In [76]:
loss_fn=F.mse_loss

In [77]:
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(7204.6592, grad_fn=<MseLossBackward0>)


In [78]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [81]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred=model(xb)
            loss=loss_fn(pred,yb)
            loss.backward()
            opt.step() #update parameters
            opt.zero_grad()
        if (epoch+1)%100==0:
              print('Epoch[{}/{}], Loss:{:4f}'.format(epoch+1, num_epochs, loss.item()))




In [84]:
fit(10000, model,loss_fn, opt, train_dl)

Epoch[10/10000], Loss:0.467623
Epoch[20/10000], Loss:0.801476
Epoch[30/10000], Loss:0.681260
Epoch[40/10000], Loss:0.680312
Epoch[50/10000], Loss:0.707661
Epoch[60/10000], Loss:0.609641
Epoch[70/10000], Loss:0.554809
Epoch[80/10000], Loss:0.619585
Epoch[90/10000], Loss:0.741613
Epoch[100/10000], Loss:0.542165
Epoch[110/10000], Loss:0.484739
Epoch[120/10000], Loss:0.473692
Epoch[130/10000], Loss:0.511166
Epoch[140/10000], Loss:0.528239
Epoch[150/10000], Loss:0.692004
Epoch[160/10000], Loss:0.603827
Epoch[170/10000], Loss:0.573502
Epoch[180/10000], Loss:0.447154
Epoch[190/10000], Loss:0.688666
Epoch[200/10000], Loss:0.653331
Epoch[210/10000], Loss:0.575232
Epoch[220/10000], Loss:0.589293
Epoch[230/10000], Loss:0.700450
Epoch[240/10000], Loss:0.529276
Epoch[250/10000], Loss:0.651281
Epoch[260/10000], Loss:0.541804
Epoch[270/10000], Loss:0.609387
Epoch[280/10000], Loss:0.413596
Epoch[290/10000], Loss:0.690610
Epoch[300/10000], Loss:0.793928
Epoch[310/10000], Loss:0.448169
Epoch[320/10000],

In [85]:
preds=model(inputs)

In [86]:
preds

tensor([[ 57.1833,  70.3307],
        [ 82.1646, 100.6668],
        [118.6641, 132.9633],
        [ 21.0593,  37.0180],
        [101.9072, 119.1476],
        [ 57.1833,  70.3307],
        [ 82.1646, 100.6668],
        [118.6641, 132.9633],
        [ 21.0593,  37.0180],
        [101.9072, 119.1476],
        [ 57.1833,  70.3307],
        [ 82.1646, 100.6668],
        [118.6641, 132.9633],
        [ 21.0593,  37.0180],
        [101.9072, 119.1476]], grad_fn=<AddmmBackward0>)

In [87]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])